name = "VortexLattice"
uuid = "7a09bdf8-3785-11e9-0bdd-57d0ec69af3f"
authors = ["Taylor McDonnell <taylormcd@byu.edu", "Andrew Ning <aning@byu.edu>"]
version = "0.1.8"

[deps]
CCBlade = "e1828068-15df-11e9-03e4-ef195ea46fa4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VSPGeom = "9b3f6a95-fce2-4bc5-94a2-f99b39986ea6"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CCBlade = "0.2"
DelimitedFiles = "1"
FLOWMath = "0.4"
StaticArrays = "0.12, 1.0"
VSPGeom = "0.6"
WriteVTK = "1.8"
julia = "1.5"
