name = "VortexLattice"
uuid = "7a09bdf8-3785-11e9-0bdd-57d0ec69af3f"
authors = ["Taylor McDonnell <taylormcd@byu.edu", "Andrew Ning <aning@byu.edu>"]
version = "0.1.6"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VSPGeom = "9b3f6a95-fce2-4bc5-94a2-f99b39986ea6"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
Interpolations = "0.13, 0.14"
StaticArrays = "0.12, 1.0"
WriteVTK = "1.8"
julia = "1.5"
